/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.14.0-SNAPSHOT).
 * https://openapi-generator.tech
 * Do not edit the class manually.
*/
package com.tanacchi.pantry.planner.api.controller

import com.tanacchi.pantry.planner.api.model.Model400ErrorMessage
import com.tanacchi.pantry.planner.api.model.Model404ErrorMessage
import com.tanacchi.pantry.planner.api.model.Model500ErrorMessage
import com.tanacchi.pantry.planner.api.model.Pantry
import io.swagger.v3.oas.annotations.*
import io.swagger.v3.oas.annotations.enums.*
import io.swagger.v3.oas.annotations.media.*
import io.swagger.v3.oas.annotations.responses.*
import io.swagger.v3.oas.annotations.security.*
import org.springframework.http.HttpStatus
import org.springframework.http.MediaType
import org.springframework.http.ResponseEntity

import org.springframework.web.bind.annotation.*
import org.springframework.validation.annotation.Validated
import org.springframework.web.context.request.NativeWebRequest
import org.springframework.beans.factory.annotation.Autowired

import jakarta.validation.constraints.DecimalMax
import jakarta.validation.constraints.DecimalMin
import jakarta.validation.constraints.Email
import jakarta.validation.constraints.Max
import jakarta.validation.constraints.Min
import jakarta.validation.constraints.NotNull
import jakarta.validation.constraints.Pattern
import jakarta.validation.constraints.Size
import jakarta.validation.Valid

import kotlin.collections.List
import kotlin.collections.Map

@RestController
@Validated
interface PantriesApi {

    @Operation(
        tags = ["Pantry",],
        summary = "ユーザーIDでパントリーの詳細を取得します",
        operationId = "pantriesByUserUserIdDetailGet",
        description = """指定したユーザーIDに紐づくパントリーを取得します。""",
        responses = [
            ApiResponse(responseCode = "200", description = "パントリー一覧の取得に成功しました", content = [Content(array = ArraySchema(schema = Schema(implementation = Pantry::class)))]),
            ApiResponse(responseCode = "404", description = "リソースが見つかりません", content = [Content(schema = Schema(implementation = Model404ErrorMessage::class))]),
            ApiResponse(responseCode = "400", description = "不正なリクエスト", content = [Content(schema = Schema(implementation = Model400ErrorMessage::class))]),
            ApiResponse(responseCode = "500", description = "サーバーエラー", content = [Content(schema = Schema(implementation = Model500ErrorMessage::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/pantries/by-user/{userId}/detail"],
            produces = ["application/json"]
    )
    fun pantriesByUserUserIdDetailGet(@Parameter(description = "ユーザーID", required = true) @PathVariable("userId") userId: kotlin.Int): ResponseEntity<List<Pantry>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Pantry",],
        summary = "ユーザーIDでパントリーを取得します",
        operationId = "pantriesByUserUserIdGet",
        description = """指定したユーザーIDに紐づくパントリーを取得します。""",
        responses = [
            ApiResponse(responseCode = "200", description = "パントリー一覧の取得に成功しました", content = [Content(array = ArraySchema(schema = Schema(implementation = Pantry::class)))]),
            ApiResponse(responseCode = "404", description = "リソースが見つかりません", content = [Content(schema = Schema(implementation = Model404ErrorMessage::class))]),
            ApiResponse(responseCode = "400", description = "不正なリクエスト", content = [Content(schema = Schema(implementation = Model400ErrorMessage::class))]),
            ApiResponse(responseCode = "500", description = "サーバーエラー", content = [Content(schema = Schema(implementation = Model500ErrorMessage::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/pantries/by-user/{userId}"],
            produces = ["application/json"]
    )
    fun pantriesByUserUserIdGet(@Parameter(description = "ユーザーID", required = true) @PathVariable("userId") userId: kotlin.Int): ResponseEntity<List<Pantry>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Pantry",],
        summary = "パントリー一覧を取得します",
        operationId = "pantriesGet",
        description = """クエリパラメータで検索条件を指定してパントリーのリストを取得します。""",
        responses = [
            ApiResponse(responseCode = "200", description = "パントリー一覧の取得に成功しました", content = [Content(array = ArraySchema(schema = Schema(implementation = Pantry::class)))]),
            ApiResponse(responseCode = "400", description = "不正なリクエスト", content = [Content(schema = Schema(implementation = Model400ErrorMessage::class))]),
            ApiResponse(responseCode = "500", description = "サーバーエラー", content = [Content(schema = Schema(implementation = Model500ErrorMessage::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/pantries"],
            produces = ["application/json"]
    )
    fun pantriesGet(): ResponseEntity<List<Pantry>> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Pantry",],
        summary = "指定IDのパントリーを削除します",
        operationId = "pantriesIdDelete",
        description = """パントリーを削除します。""",
        responses = [
            ApiResponse(responseCode = "204", description = "パントリーの削除に成功しました"),
            ApiResponse(responseCode = "404", description = "リソースが見つかりません", content = [Content(schema = Schema(implementation = Model404ErrorMessage::class))]),
            ApiResponse(responseCode = "400", description = "不正なリクエスト", content = [Content(schema = Schema(implementation = Model400ErrorMessage::class))]),
            ApiResponse(responseCode = "500", description = "サーバーエラー", content = [Content(schema = Schema(implementation = Model500ErrorMessage::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.DELETE],
            value = ["/pantries/{id}"],
            produces = ["application/json"]
    )
    fun pantriesIdDelete(@Parameter(description = "パントリーID", required = true) @PathVariable("id") id: kotlin.Int): ResponseEntity<Unit> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Pantry",],
        summary = "指定IDのパントリーの詳細を取得します",
        operationId = "pantriesIdDetailGet",
        description = """パントリーのプライマリキーであるIDを指定して取得します。""",
        responses = [
            ApiResponse(responseCode = "200", description = "パントリーの取得に成功しました", content = [Content(schema = Schema(implementation = Pantry::class))]),
            ApiResponse(responseCode = "404", description = "リソースが見つかりません", content = [Content(schema = Schema(implementation = Model404ErrorMessage::class))]),
            ApiResponse(responseCode = "400", description = "不正なリクエスト", content = [Content(schema = Schema(implementation = Model400ErrorMessage::class))]),
            ApiResponse(responseCode = "500", description = "サーバーエラー", content = [Content(schema = Schema(implementation = Model500ErrorMessage::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/pantries/{id}/detail"],
            produces = ["application/json"]
    )
    fun pantriesIdDetailGet(@Parameter(description = "パントリーID", required = true) @PathVariable("id") id: kotlin.Int): ResponseEntity<Pantry> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Pantry",],
        summary = "指定IDのパントリーを取得します",
        operationId = "pantriesIdGet",
        description = """パントリーのプライマリキーであるIDを指定して取得します。""",
        responses = [
            ApiResponse(responseCode = "200", description = "パントリーの取得に成功しました", content = [Content(schema = Schema(implementation = Pantry::class))]),
            ApiResponse(responseCode = "404", description = "リソースが見つかりません", content = [Content(schema = Schema(implementation = Model404ErrorMessage::class))]),
            ApiResponse(responseCode = "400", description = "不正なリクエスト", content = [Content(schema = Schema(implementation = Model400ErrorMessage::class))]),
            ApiResponse(responseCode = "500", description = "サーバーエラー", content = [Content(schema = Schema(implementation = Model500ErrorMessage::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.GET],
            value = ["/pantries/{id}"],
            produces = ["application/json"]
    )
    fun pantriesIdGet(@Parameter(description = "パントリーID", required = true) @PathVariable("id") id: kotlin.Int): ResponseEntity<Pantry> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Pantry",],
        summary = "指定IDのパントリー情報を更新します",
        operationId = "pantriesIdPut",
        description = """パントリーの情報を更新します。""",
        responses = [
            ApiResponse(responseCode = "200", description = "パントリーの更新に成功しました", content = [Content(schema = Schema(implementation = Pantry::class))]),
            ApiResponse(responseCode = "404", description = "リソースが見つかりません", content = [Content(schema = Schema(implementation = Model404ErrorMessage::class))]),
            ApiResponse(responseCode = "400", description = "不正なリクエスト", content = [Content(schema = Schema(implementation = Model400ErrorMessage::class))]),
            ApiResponse(responseCode = "500", description = "サーバーエラー", content = [Content(schema = Schema(implementation = Model500ErrorMessage::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.PUT],
            value = ["/pantries/{id}"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun pantriesIdPut(@Parameter(description = "パントリーID", required = true) @PathVariable("id") id: kotlin.Int,@Parameter(description = "", required = true) @Valid @RequestBody pantry: Pantry): ResponseEntity<Pantry> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }

    @Operation(
        tags = ["Pantry",],
        summary = "新しいパントリーを作成します",
        operationId = "pantriesPost",
        description = """createdAt, updatedAtはリクエストボディに含めずに作成してください。""",
        responses = [
            ApiResponse(responseCode = "201", description = "パントリーの作成に成功しました", content = [Content(schema = Schema(implementation = Pantry::class))]),
            ApiResponse(responseCode = "400", description = "不正なリクエスト", content = [Content(schema = Schema(implementation = Model400ErrorMessage::class))]),
            ApiResponse(responseCode = "500", description = "サーバーエラー", content = [Content(schema = Schema(implementation = Model500ErrorMessage::class))])
        ]
    )
    @RequestMapping(
            method = [RequestMethod.POST],
            value = ["/pantries"],
            produces = ["application/json"],
            consumes = ["application/json"]
    )
    fun pantriesPost(@Parameter(description = "", required = true) @Valid @RequestBody pantry: Pantry): ResponseEntity<Pantry> {
        return ResponseEntity(HttpStatus.NOT_IMPLEMENTED)
    }
}
