[build]
command = "pnpm prisma generate && pnpm run build"
publish = "build/client"
base = "ui"

[functions]
directory = "netlify/functions"

[functions.default]
included_files = [
  "node_modules/.prisma/**",
  "prisma/schema.prisma"
]
