name: Deploy api to Vercel

env:
  VERCEL_ORG_ID: ${{ secrets.PLANNER_API_VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.PLANNER_API_VERCEL_PROJECT_ID }}

on:
  workflow_dispatch:
    inputs:
      ref:
        description: branch|tag|SHA to checkout
        default: "main"
        required: false
  release:
    types: [created]

jobs:
  Deploy-Production:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: '22'

      - uses: pnpm/action-setup@v4 # バージョンは package.json に記載のものを使用

      - name: Install Vercel CLI
        run: pnpm install --global vercel@latest

      - name: Generate Prisma Client
        run: npx prisma generate
        working-directory: ./api

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.PLANNER_API_VERCEL_TOKEN }}
        working-directory: ./api

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.PLANNER_API_VERCEL_TOKEN }}
        working-directory: ./api

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.PLANNER_API_VERCEL_TOKEN }}
        working-directory: ./api
